### ISSUE TITLE
About KITTI data set reading problems

### ISSUE THREAD

**Issue by xiang-1208** [jedeschaud/ct_icp#1]
As we all know, KITTI's official data set is stored as .bin format, while your code is read in .ply format. I wonder if I made a mistake.

**Comment by qsisi** [comment]
> In our code, we wanted to unify the reading of LiDAR data with a single format of binary type ply with timestamp. Indeed, KITTI distributes its Velodyne data in .bin but without timestamp. We provide KITTI data converted to ply binary downloadable in this folder: https://cloud.mines-paristech.fr/index.php/s/UwgVFtiTOmrgKp5 The password is : **npm3d**

Hello, the KITTI data processed by you is too large for me to download, can you provide the processing scripts to convert the original *.bin in KITTI odometry to *.ply? In that way, I can do that processing step myself.
