### ISSUE TITLE
kitti timestamps

### ISSUE THREAD

**Issue by dongfangzhou1108** [jedeschaud/ct_icp#2]
great appreciate with opening your great work！
first, can you provide dataset passcord to me， no one relpy in mail，
second， And when I see kitti website, the raw point cloud data do not have time information except scan begin and end time,
How do you get the time information?

thanks a lot
best wishes！

**Comment by jedeschaud** [comment]
Hello,
The password for the dataset folder is : **npm3d**
CT-ICP does not need the real timestamp of points but only the relative timestamp inside one scan.
For KITTI dataset, we compute the timestamp from the azimuth of points in a scan.
Here the Python line to compute the timestamp :
`data[:,3] = float(i-FIRST_INDEX_FRAME)/10.0 + (-np.arctan2(data[:,1], data[:,0])/np.pi+1.0)*0.05`

Best Regards

**Comment by dongfangzhou1108** [comment]
Thank you very much！

**Comment by dongfangzhou1108** [comment]
sorry，Can you provide the python code for me？thanks a lot！

**Comment by dongfangzhou1108** [comment]
hi，i find the begin time of the first frame in sync raw data and unsync raw data is not the same, do you notice this point, when produce experiments?
for example in 04(unsync) timestamps in velodyne is
2011-09-30 11:50:40.036777909
2011-09-30 11:50:40.140937618
2011-09-30 11:50:40.245121652
2011-09-30 11:50:40.349304485
and sync is from 
2011-09-30 11:50:40.349304485
when i produce rosbag or .ply, may i need produce from the 4th frame in unsync raw data or just use sync data?

thanks a lot!

**Comment by dongfangzhou1108** [comment]
> [PLY_Scans_from_KITTI_raw_data.zip](https://github.com/jedeschaud/ct_icp/files/7372121/PLY_Scans_from_KITTI_raw_data.zip)

hello,can you provide your PLY_Scans_from_KITTI_correct for me?
use your PLY_Scans_from_KITTI_raw_data do not fit the Kitti_correct, make a big APE/RPE in slam;
thank you!
