### ISSUE TITLE
debugging at vscode

### ISSUE THREAD

**Issue by D0NGJE** [jedeschaud/ct_icp#20]
Hi.

I tried to debugging slam.cpp at vscode. 

I got a syntax error like this photo.
![image](https://user-images.githubusercontent.com/103257795/163959083-f376aa0f-d178-408a-9442-96158507e2bf.png)

I don't know what is the problem. 

I hope you reply

**Comment by pdell-kitware** [comment]
Hi, 

I think you have a problem with the `viz3d`  installation of branch master, 
Have you installed viz3d in the superbuild ? 

Can you describe the installation messages ?

Best regards

**Comment by D0NGJE** [comment]
thank you for your reply.

I using debugging mode in vscode. 
![image](https://user-images.githubusercontent.com/103257795/163969905-212af980-10b5-497f-9f55-1024d54d2bd1.png)

By the way, I successfully built and run it, but when I pressed F5 for debugging in vscode the above error occured .<br/>

[CT-ICP]
The command I input,
~~~bash
$ ./ct_icp_build.sh Release "Unix Makefiles" ON ON 
~~~

![image](https://user-images.githubusercontent.com/103257795/163970681-1f7540a2-f2bd-47ce-a3b7-9b028b2afb1e.png)


Best regards.

**Comment by pdell-kitware** [comment]
So building the SLAM seems to work, 

But you can't compile it on your IDE, is that right ?

Have you tried running the slam similarly to the readme instuctions ? 
Running the command `./slam -c <path-to-config>`

Does this work ?

I am not familiar with vscode, so I can't help you on this problem. But you can try to comment all the code between 
the preprocessor #if CT_ICP_WITH_VIZ see if its compiles

**Comment by D0NGJE** [comment]
./slam -c default_config.yaml is work.

Thank you for your reply.
