### ISSUE TITLE
Working on Ubuntu 20.04 (ROS Noetic)

### ISSUE THREAD

**Issue by bigbigpark** [jedeschaud/ct_icp#43]
Hi, again. <br/>
I'd appreciate for you to share the ROS wrapping. <br/>
Is it work on Ubuntu 20.04 (ROS Noetic) ? <br/>
Actually, I have trouble with installing `SuperBuild`.

**Comment by pdell-kitware** [comment]
Hi, 

> I'd appreciate for you to share the ROS wrapping.

Not sure I understand the first part of the question, the ros wrapping is located at `<ct_icp_root>ros/catkin_ws` (see the instructions in the readme)

 > Is it work on Ubuntu 20.04 (ROS Noetic) ?

I haven't tested it, and I will not have much time to do it, but I suggest you try (there is no reasons to my knowledge it shouldn't), 
If you have any problem don't hesitate to print the error messages here

> Actually, I have trouble with installing `SuperBuild`.

If you want me to help you, please give me some error messages to work with :)

(And do not forget to pull the last branch of master, which changed a lot recently)
