### ISSUE TITLE
[Ceres] double free or corruption (out), Aborted (core dumped)

### ISSUE THREAD

**Issue by bigbigpark** [jedeschaud/ct_icp#49]
Hi <br/>

I am using [CT-ICP, ICRA 2022](https://github.com/jedeschaud/ct_icp/releases/tag/icra_2022) and found some errors in `ct_icp.cpp`. I successfully compile and built this package. <br/>
When I run this code, an error occured in the function of **CT_ICP_CERES**. <br/>
In my terminal it says,
~~~bash
double free or corruption (out)
Aborted (core dumped)
~~~
I debugged that code, I found where the problem starts. <br/>
~~~c++
ceres::Solve(ceres_options, problem.get(), &summary);
~~~

Here is my environment. <br/>
Ubuntu 20.04 <br/>
cmake 3.18.0 <br/>
gcc/g++ 9.4.0
Ceres solver 2.1.0 <br/>
robin-map 1.0.0 <br/>

How can I fix this problem?

**Comment by yeyanan93** [comment]
请问你是怎么解决的？@bigbigpark
