### ISSUE TITLE
Choice of interpolation method for the time continuous representation.

### ISSUE THREAD

**Issue by KaziiBotashev** [jedeschaud/ct_icp#60]
Hello! Thank you for such bright project and for the code release :)

I have a question related to paper. Can you please explain a motivation behind choosing the interpolation method for time continuous representation? You use a separate linear interpolation (slerp) for the rotation (S03) and translation (R^3). Did you try any other method such are linear interpolation of SE3 elements or B-splines? Why did you decide to use a such particular way?

I really appreciate any help you might provide.
Thank you in advance :)

**Comment by pierdell** [comment]
Hi, thanks for the kind words  :)

So I refer you to our article for the motivation behind using a continuous-time registration 
(Basically to handle the distortion of the LiDAR), 

Concerning the details of the implementation:

We chose linear Interpolation over B-splines for simplicity first, and haven't had time to test using B-spline, 
And  though it is definitely on our stack, we don't really think that this will be the determining factor 
To gain precision with respect to other issues (map representation, loop closure, error minimized, etc...), 

But clearly using a B-Spline should be nicer for other reasons (notably if you want to use an IMU), 
So we are still thinking on it :)

Hope this helps, 

Best Regards,
