### ISSUE TITLE
kitti-correct point cloud distort

### ISSUE THREAD

**Issue by dongfangzhou1108** [jedeschaud/ct_icp#8]
hi, appreciate with your work.
i notice "The odometry benchmark proposes motion-corrected scans (using the camera to distort the scans): we called this KITTI-corrected".
where did you find the method of kitti distort point cloud using camera? can you tell me? 
thanks.

**Comment by jedeschaud** [comment]
Hello, it is an error. They use the GPS/IMU system to compensate the egomotion, it is written in their paper page 2: 
[Link](http://www.cvlibs.net/publications/Geiger2012CVPR.pdf)
I will correct it in our camera-ready version of the paper (accepted at ICRA2022).
Best Regards.
